FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
COPY .env.local ./
RUN yarn build
EXPOSE 3000
CMD  ["yarn", "start"]

# production stage
# FROM nginx:stable-alpine as production-stage
# COPY --from=build-stage /app/.next /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]