import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Button from "@mui/material/Button";
import TextField from "@mui/material/TextField";
import { purple } from "@mui/material/colors";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { useRouter } from "next/router";
// import LoadingButton from "@mui/lab/LoadingButton";
import styles from "../styles/Login.module.css";
import { style } from "@mui/system";

// const theme = createTheme({
//   palette: {
//     primary: {
//       // Purple and green play nicely together.
//       main: "#ffffff",
//       darker: "#053e85",
//     },
//     secondary: {
//       // This is green.A700 as hex.
//       main: "#11cb5f",
//     },
//   },
// });

export default function Home() {
  // const [text, setText] = useState();
  const router = useRouter();
  return (
    // <ThemeProvider theme={theme}>
    <div className={styles.container}>
      <div style={{ minWidth: "40%", backgroundColor: "#0013FF" }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Bem vindo!
            {/* <a href="https://nextjs.org">Next.js!</a> */}
          </h1>

          <p className={styles.description}>
            Logue para começar!
            {/* <code className={styles.code}>pages/index.js</code> */}
          </p>
          <Image
            src="/Sign up-rafiki.svg"
            alt="Sign up page"
            width={450}
            height={450}
          />
          <div className={styles.grid}>
            {/* <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
              </a>
              
            <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>
            
            <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
            >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
            
            <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a> */}
          </div>
        </main>

        {/* <footer className={styles.footer}>
          <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
            <Image
            src="/vercel.svg"
            alt="Vercel Logo"
            width={72}
            height={16}
            />
            </span>
            </a>
          </footer> */}
      </div>
      <div
        style={{
          backgroundColor: "#EAEAEA",
          display: "flex",
          width: "100%",
          flexDirection: "column",
        }}
      >
        <div className={styles.formContainer}>
          <div className={styles.floatContainer}>
            <h1 className={styles.titleForm}>
              Login
            </h1>
            <TextField
              label="Login"
              className={styles.textFieldLogin}
            ></TextField>
            <TextField
              type="password"
              label="Senha"
              className={styles.textFieldPassword}
            >
              {" "}
            </TextField>
            <div
              style={{
                margin: "20px",
                display: "flex",
                width: "235px",
                alignSelf: "center",
              }}
            >
              <Button
                onClick={() => router.push('/home')}
                style={{
                  display: "flex",
                  justifyContent: "center",
                  width: "100%",
                }}
                size="large"
                variant="contained"
              >
                ENTRAR
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
    // </ThemeProvider>
  );
}
